spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ElectricityWork
    username: postgres
    password: yblud228
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 1010